"""
ml/train_model.py
──────────────────
Trains an XGBoost classifier on the labeled training data generated by
generate_training_data.py.

What it does:
  1. Loads the labeled CSV
  2. Splits chronologically (not randomly — time series must never shuffle)
  3. Trains separate long and short classifiers
  4. Evaluates on out-of-sample data
  5. Reports feature importance (tells you which indicators actually matter)
  6. Saves models as .json files for use by the backtester and live engine
  7. Runs walk-forward validation across 3 time windows

Usage:
    pip install xgboost scikit-learn
    python ml/train_model.py --data ml/data/BTC_USDT_4h_training.csv
    python ml/train_model.py --data ml/data/ETH_USDT_4h_training.csv --direction short
"""

import argparse
import json
import logging
import os
import sys
from datetime import datetime

import numpy as np
import pandas as pd

try:
    import xgboost as xgb
    from sklearn.metrics import (
        accuracy_score, classification_report,
        roc_auc_score, precision_score, recall_score,
    )
    from sklearn.calibration import CalibratedClassifierCV
except ImportError:
    print("Missing dependencies. Run: pip install xgboost scikit-learn")
    sys.exit(1)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s  %(message)s",
    datefmt="%H:%M:%S",
)
log = logging.getLogger("ml.train")

FEATURE_COLS = [
    "rsi", "macd_hist", "macd_hist_prev", "adx",
    "ema_spread_pct", "atr_pct", "vol_ratio",
    "bb_width", "bb_squeeze",
    "ema_bull", "ema_bear", "ema_bull_4h", "ema_bear_4h", "adx_4h",
]

# Regime one-hot encoding — the model needs regime as numeric
REGIMES = ["ranging", "trending_bull", "trending_bear", "high_volatility"]


def encode_features(df: pd.DataFrame) -> pd.DataFrame:
    """Add one-hot regime columns and ensure all features are numeric."""
    out = df.copy()
    for r in REGIMES:
        out[f"regime_{r}"] = (out["regime"] == r).astype(int)
    return out


def get_feature_cols(df: pd.DataFrame) -> list[str]:
    exclude = ["time", "open", "high", "low", "close", "volume", "regime", 
               "label_long", "label_short", "forward_return_pct", "forward_bars_used"]
    base = [c for c in df.columns if c not in exclude and not c.startswith("regime_")]
    regime_cols = [f"regime_{r}" for r in REGIMES]
    return [c for c in base + regime_cols if c in df.columns]

def train_direction(
    df: pd.DataFrame,
    direction: str,    # 'long' or 'short'
    train_pct: float,
    output_dir: str,
    slug: str,
) -> dict:
    """
    Train a classifier for one direction (long or short).
    Uses chronological train/test split.
    Returns evaluation metrics.
    """
    label_col = f"label_{direction}"
    if label_col not in df.columns:
        log.error("Column %s not found in data", label_col)
        return {}

    df = encode_features(df)
    feat_cols = get_feature_cols(df)

    # Drop rows with NaN features
    df_clean = df.dropna(subset=feat_cols + [label_col]).reset_index(drop=True)
    log.info("%s direction: %d clean rows", direction, len(df_clean))

    if len(df_clean) < 100:
        log.error("Insufficient data (%d rows). Need 100+ for meaningful training.",
                  len(df_clean))
        return {}

    # Chronological split — NEVER shuffle time series
    split = int(len(df_clean) * train_pct)
    X_train = df_clean[feat_cols].iloc[:split].values
    y_train = df_clean[label_col].iloc[:split].values
    X_test  = df_clean[feat_cols].iloc[split:].values
    y_test  = df_clean[label_col].iloc[split:].values

    log.info("Train: %d rows (%s → %s)  |  Test: %d rows (%s → %s)",
             len(X_train),
             str(df_clean["time"].iloc[0])[:10],
             str(df_clean["time"].iloc[split-1])[:10],
             len(X_test),
             str(df_clean["time"].iloc[split])[:10],
             str(df_clean["time"].iloc[-1])[:10])

    # Class balance: the dataset is naturally imbalanced (more losses than wins)
    # scale_pos_weight corrects for this
    pos = y_train.sum()
    neg = len(y_train) - pos
    spw = neg / max(pos, 1)
    log.info("Class balance — wins: %d  losses: %d  scale_pos_weight: %.2f",
             pos, neg, spw)

    # XGBoost model
    # These hyperparameters are conservative to prevent overfitting on small data.
    # max_depth=4 and min_child_weight=10 prevent the tree from memorising noise.
    model = xgb.XGBClassifier(
        n_estimators=300,
        max_depth=4,             # shallow trees = less overfitting
        learning_rate=0.05,      # slow learning = more robust
        subsample=0.8,           # row sampling
        colsample_bytree=0.8,    # feature sampling
        min_child_weight=10,     # min samples in a leaf — key overfitting guard
        scale_pos_weight=spw,    # handle class imbalance
        eval_metric="logloss",
        early_stopping_rounds=30,
        random_state=42,
        verbosity=0,
    )

    model.fit(
        X_train, y_train,
        eval_set=[(X_test, y_test)],
        verbose=False,
    )

    # Evaluation
    y_pred       = model.predict(X_test)
    y_prob       = model.predict_proba(X_test)[:, 1]
    accuracy     = accuracy_score(y_test, y_pred)
    precision    = precision_score(y_test, y_pred, zero_division=0)
    recall       = recall_score(y_test, y_pred, zero_division=0)
    auc          = roc_auc_score(y_test, y_prob) if len(np.unique(y_test)) > 1 else 0.5

    print(f"\n{'═'*55}")
    print(f"  {direction.upper()} model — out-of-sample results")
    print(f"{'═'*55}")
    print(f"  Accuracy:   {accuracy*100:>6.1f}%")
    print(f"  Precision:  {precision*100:>6.1f}%  (of predicted wins, how many were real wins)")
    print(f"  Recall:     {recall*100:>6.1f}%  (of real wins, how many did we catch)")
    print(f"  AUC-ROC:    {auc:>6.3f}  (0.5 = random, 1.0 = perfect)")
    print(f"\n  The AUC is the most important metric.")
    print(f"  AUC > 0.55 = model has learned something real")
    print(f"  AUC > 0.60 = useful edge")
    print(f"  AUC > 0.65 = strong edge")
    print()

    # Feature importance — what the model actually learned
    importance = dict(zip(feat_cols, model.feature_importances_))
    importance_sorted = sorted(importance.items(), key=lambda x: x[1], reverse=True)
    print(f"  Feature importance (what the model learned matters):")
    for feat, imp in importance_sorted[:10]:
        bar = "█" * int(imp * 200)
        print(f"    {feat:22}  {imp:.4f}  {bar}")
    print()

    # Optimal threshold: find the probability cutoff that maximises precision
    # We want high precision (when we trade, we win) over high recall
    thresholds    = np.arange(0.45, 0.80, 0.05)
    best_thresh   = 0.5
    best_precision= 0
    print(f"  Threshold sweep (find best trade filter):")
    print(f"    {'Threshold':>10}  {'Trades':>8}  {'Precision':>10}  {'Coverage':>10}")
    for t in thresholds:
        mask      = y_prob >= t
        n_trades  = mask.sum()
        if n_trades == 0:
            continue
        prec      = y_test[mask].mean()
        coverage  = n_trades / len(y_test) * 100
        marker    = " ← recommended" if 0.55 <= prec <= 0.70 and n_trades >= 10 else ""
        print(f"    {t:>10.2f}  {n_trades:>8}  {prec*100:>9.1f}%  {coverage:>9.1f}%{marker}")
        if prec > best_precision and n_trades >= 10:
            best_precision = prec
            best_thresh    = t
    print()
    print(f"  Recommended threshold: {best_thresh:.2f}  "
          f"(precision {best_precision*100:.1f}%)")
    print(f"{'═'*55}")

    # Save model
    os.makedirs(output_dir, exist_ok=True)
    model_path = os.path.join(output_dir, f"{slug}_{direction}.json")
    model.save_model(model_path)

    # Save metadata alongside the model
    meta = {
        "direction":       direction,
        "slug":            slug,
        "feature_cols":    feat_cols,
        "trained_at":      datetime.now().isoformat(),
        "train_rows":      int(len(X_train)),
        "test_rows":       int(len(X_test)),
        "accuracy":        round(accuracy, 4),
        "precision":       round(precision, 4),
        "recall":          round(recall, 4),
        "auc_roc":         round(auc, 4),
        "recommended_threshold": round(best_thresh, 2),
        "feature_importance": {k: round(float(v), 4) for k, v in importance_sorted},
    }
    meta_path = model_path.replace(".json", "_meta.json")
    with open(meta_path, "w") as f:
        json.dump(meta, f, indent=2)

    log.info("Model saved → %s", model_path)
    log.info("Metadata  → %s", meta_path)
    return meta


def walk_forward_eval(
    df: pd.DataFrame,
    direction: str,
    n_windows: int = 3,
) -> None:
    """
    Walk-forward evaluation: train on first 70% of each window, test on last 30%.
    This is the only valid way to evaluate a time-series ML model.
    A good model should have AUC > 0.55 across all windows.
    """
    label_col = f"label_{direction}"
    df = encode_features(df).dropna(subset=get_feature_cols(df) + [label_col])
    feat_cols = get_feature_cols(df)
    window = len(df) // n_windows

    print(f"\n  Walk-forward validation ({n_windows} windows) — {direction.upper()}")
    print(f"  {'Window':>8}  {'Train rows':>12}  {'Test rows':>10}  {'AUC':>8}  {'Precision':>10}")
    print("  " + "─" * 56)

    for i in range(n_windows):
        chunk  = df.iloc[i * window:(i + 1) * window].reset_index(drop=True)
        split  = int(len(chunk) * 0.7)
        X_tr   = chunk[feat_cols].iloc[:split].values
        y_tr   = chunk[label_col].iloc[:split].values
        X_te   = chunk[feat_cols].iloc[split:].values
        y_te   = chunk[label_col].iloc[split:].values

        if len(X_te) < 20 or y_te.sum() < 3:
            print(f"  {i+1:>8}  {'(skipped — insufficient data)':>40}")
            continue

        spw = (len(y_tr) - y_tr.sum()) / max(y_tr.sum(), 1)
        m   = xgb.XGBClassifier(
            n_estimators=200, max_depth=4, learning_rate=0.05,
            subsample=0.8, colsample_bytree=0.8, min_child_weight=10,
            scale_pos_weight=spw, random_state=42, verbosity=0,
        )
        m.fit(X_tr, y_tr, eval_set=[(X_te, y_te)], verbose=False)
        y_prob = m.predict_proba(X_te)[:, 1]
        y_pred = m.predict(X_te)
        auc    = roc_auc_score(y_te, y_prob) if len(np.unique(y_te)) > 1 else 0.5
        prec   = precision_score(y_te, y_pred, zero_division=0)
        mark   = " ✅" if auc > 0.55 else " ❌"
        print(f"  {i+1:>8}  {len(X_tr):>12}  {len(X_te):>10}  {auc:>7.3f}{mark}  {prec*100:>9.1f}%")

    print()
    print("  Interpretation:")
    print("  AUC > 0.55 across all windows = model is real, not overfitted")
    print("  AUC varies wildly across windows = model is memorising, not learning")


def main():
    p = argparse.ArgumentParser(description="Train XGBoost signal classifier")
    p.add_argument("--data",       required=True,  help="Path to training CSV from generate_training_data.py")
    p.add_argument("--direction",  default="both", choices=["long", "short", "both"])
    p.add_argument("--train-pct",  type=float, default=0.7)
    p.add_argument("--output-dir", default="ml/models")
    p.add_argument("--walk-forward", action="store_true",
                   help="Run walk-forward validation after training")
    args = p.parse_args()

    if not os.path.exists(args.data):
        log.error("Training data not found: %s", args.data)
        sys.exit(1)

    log.info("Loading training data: %s", args.data)
    df = pd.read_csv(args.data, parse_dates=["time"])
    log.info("%d rows, %d columns", len(df), len(df.columns))

    if len(df) < 100:
        log.error("Need at least 100 rows. Got %d.", len(df))
        log.error("Re-run generate_training_data.py with --skip-bars 1")
        sys.exit(1)

    slug = os.path.splitext(os.path.basename(args.data))[0].replace("_training", "")
    directions = ["long", "short"] if args.direction == "both" else [args.direction]

    for direction in directions:
        log.info("Training %s classifier…", direction)
        meta = train_direction(df, direction, args.train_pct, args.output_dir, slug)

        if args.walk_forward and meta:
            walk_forward_eval(df, direction)

    print("\n  Next step:")
    print(f"    python ml/backtest_with_ml.py \\")
    print(f"      --csv backtest/data/<your_file>.csv \\")
    print(f"      --model-dir {args.output_dir} \\")
    print(f"      --slug {slug}")
    print()


if __name__ == "__main__":
    main()